### ISSUE TITLE
Breaks HMR

### ISSUE THREAD

**Issue by danb-cws** [andrewcoelho/reload-html-webpack-plugin#1]
I'm not sure if this was ever supposed to work with HMR, but the 'hot-update.json' fails to load with this in place

**Comment by andrewcoelho** [comment]
This will do a hard refresh on template changes, which does indeed break HMR.

If HMR doesn't work at all with this in place though, even when no changes have been made to a template that's feeding the html-webpack-plugin, that is an issue.

Is this what you're experiencing?

**Comment by danb-cws** [comment]
Yes thats whats happening. A hard refresh would be fine by me if the js/css still worked HMR.
...just a detail really, I only have a few templates and an F5 is easy enough!

**Comment by andrewcoelho** [comment]
This library was built for a very specific use case and hasn't yet been expanded as a more general purpose solution. 

Currently we have css/js HMR working by using webpack-dev-server.

If you are using some other form of HMR like webpack-hot-middleware, I can't guarantee that it would work. 

If you'd like to see a working setup you can check out https://github.com/planetary/airframe.

Thanks!

**Comment by danb-cws** [comment]
Sorry, should have said I am using webpack-dev-server (I'm familiar with setting up webpack-hot-middleware on Express as well).  I will have a look at your solution, thanks for your time.
